classdef mav_ctrl_motorsResponse < robotics.ros.Message
    %mav_ctrl_motorsResponse MATLAB implementation of asctec_hl_comm/mav_ctrl_motorsResponse
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'asctec_hl_comm/mav_ctrl_motorsResponse' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '246eeab4e06271d99512461f49c049e7' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        MotorsRunning
    end
    
    properties (Constant, Hidden)
        PropertyList = {'MotorsRunning'} % List of non-constant message properties
        ROSPropertyList = {'motorsRunning'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = mav_ctrl_motorsResponse(msg)
            %mav_ctrl_motorsResponse Construct the message object mav_ctrl_motorsResponse
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function motorsrunning = get.MotorsRunning(obj)
            %get.MotorsRunning Get the value for property MotorsRunning
            motorsrunning = logical(obj.JavaMessage.getMotorsRunning);
        end
        
        function set.MotorsRunning(obj, motorsrunning)
            %set.MotorsRunning Set the value for property MotorsRunning
            validateattributes(motorsrunning, {'logical', 'numeric'}, {'nonempty', 'scalar'}, 'mav_ctrl_motorsResponse', 'MotorsRunning');
            
            obj.JavaMessage.setMotorsRunning(motorsrunning);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.MotorsRunning = obj.MotorsRunning;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.MotorsRunning = strObj.MotorsRunning;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.MotorsRunning = obj.MotorsRunning;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.asctec_hl_comm.mav_ctrl_motorsResponse.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.asctec_hl_comm.mav_ctrl_motorsResponse;
            obj.reload(strObj);
        end
    end
end
