classdef WaypointFeedback < robotics.ros.Message
    %WaypointFeedback MATLAB implementation of asctec_hl_comm/WaypointFeedback
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'asctec_hl_comm/WaypointFeedback' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'af0dfd31e2502a8130260fc264e2e292' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        GeometryMsgsPoint32Class = robotics.ros.msg.internal.MessageFactory.getClassForType('geometry_msgs/Point32') % Dispatch to MATLAB class for message type geometry_msgs/Point32
        StdMsgsHeaderClass = robotics.ros.msg.internal.MessageFactory.getClassForType('std_msgs/Header') % Dispatch to MATLAB class for message type std_msgs/Header
    end
    
    properties (Dependent)
        Header
        CurrentPos
        CurrentYaw
        Status
    end
    
    properties (Access = protected)
        Cache = struct('Header', [], 'CurrentPos', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'CurrentPos', 'CurrentYaw', 'Header', 'Status'} % List of non-constant message properties
        ROSPropertyList = {'current_pos', 'current_yaw', 'header', 'status'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = WaypointFeedback(msg)
            %WaypointFeedback Construct the message object WaypointFeedback
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function header = get.Header(obj)
            %get.Header Get the value for property Header
            if isempty(obj.Cache.Header)
                obj.Cache.Header = feval(obj.StdMsgsHeaderClass, obj.JavaMessage.getHeader);
            end
            header = obj.Cache.Header;
        end
        
        function set.Header(obj, header)
            %set.Header Set the value for property Header
            validateattributes(header, {obj.StdMsgsHeaderClass}, {'nonempty', 'scalar'}, 'WaypointFeedback', 'Header');
            
            obj.JavaMessage.setHeader(header.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Header)
                obj.Cache.Header.setJavaObject(header.getJavaObject);
            end
        end
        
        function currentpos = get.CurrentPos(obj)
            %get.CurrentPos Get the value for property CurrentPos
            if isempty(obj.Cache.CurrentPos)
                obj.Cache.CurrentPos = feval(obj.GeometryMsgsPoint32Class, obj.JavaMessage.getCurrentPos);
            end
            currentpos = obj.Cache.CurrentPos;
        end
        
        function set.CurrentPos(obj, currentpos)
            %set.CurrentPos Set the value for property CurrentPos
            validateattributes(currentpos, {obj.GeometryMsgsPoint32Class}, {'nonempty', 'scalar'}, 'WaypointFeedback', 'CurrentPos');
            
            obj.JavaMessage.setCurrentPos(currentpos.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.CurrentPos)
                obj.Cache.CurrentPos.setJavaObject(currentpos.getJavaObject);
            end
        end
        
        function currentyaw = get.CurrentYaw(obj)
            %get.CurrentYaw Get the value for property CurrentYaw
            currentyaw = single(obj.JavaMessage.getCurrentYaw);
        end
        
        function set.CurrentYaw(obj, currentyaw)
            %set.CurrentYaw Set the value for property CurrentYaw
            validateattributes(currentyaw, {'numeric'}, {'nonempty', 'scalar'}, 'WaypointFeedback', 'CurrentYaw');
            
            obj.JavaMessage.setCurrentYaw(currentyaw);
        end
        
        function status = get.Status(obj)
            %get.Status Get the value for property Status
            status = char(obj.JavaMessage.getStatus);
        end
        
        function set.Status(obj, status)
            %set.Status Set the value for property Status
            validateattributes(status, {'char'}, {}, 'WaypointFeedback', 'Status');
            
            obj.JavaMessage.setStatus(status);
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Header = [];
            obj.Cache.CurrentPos = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.CurrentYaw = obj.CurrentYaw;
            cpObj.Status = obj.Status;
            
            % Recursively copy compound properties
            cpObj.Header = copy(obj.Header);
            cpObj.CurrentPos = copy(obj.CurrentPos);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.CurrentYaw = strObj.CurrentYaw;
            obj.Status = strObj.Status;
            obj.Header = feval([obj.StdMsgsHeaderClass '.loadobj'], strObj.Header);
            obj.CurrentPos = feval([obj.GeometryMsgsPoint32Class '.loadobj'], strObj.CurrentPos);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.CurrentYaw = obj.CurrentYaw;
            strObj.Status = obj.Status;
            strObj.Header = saveobj(obj.Header);
            strObj.CurrentPos = saveobj(obj.CurrentPos);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.asctec_hl_comm.WaypointFeedback.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.asctec_hl_comm.WaypointFeedback;
            obj.reload(strObj);
        end
    end
end
