classdef GpsCustomCartesian < robotics.ros.Message
    %GpsCustomCartesian MATLAB implementation of asctec_hl_comm/GpsCustomCartesian
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'asctec_hl_comm/GpsCustomCartesian' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '5d2c0118ba9eb587c756024a82d4d4a6' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        GeometryMsgsPointClass = robotics.ros.msg.internal.MessageFactory.getClassForType('geometry_msgs/Point') % Dispatch to MATLAB class for message type geometry_msgs/Point
        StdMsgsHeaderClass = robotics.ros.msg.internal.MessageFactory.getClassForType('std_msgs/Header') % Dispatch to MATLAB class for message type std_msgs/Header
    end
    
    properties (Dependent)
        Header
        Position
        VelocityX
        VelocityY
        PositionCovariance
        VelocityCovariance
    end
    
    properties (Access = protected)
        Cache = struct('Header', [], 'Position', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Header', 'Position', 'PositionCovariance', 'VelocityCovariance', 'VelocityX', 'VelocityY'} % List of non-constant message properties
        ROSPropertyList = {'header', 'position', 'position_covariance', 'velocity_covariance', 'velocity_x', 'velocity_y'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = GpsCustomCartesian(msg)
            %GpsCustomCartesian Construct the message object GpsCustomCartesian
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function header = get.Header(obj)
            %get.Header Get the value for property Header
            if isempty(obj.Cache.Header)
                obj.Cache.Header = feval(obj.StdMsgsHeaderClass, obj.JavaMessage.getHeader);
            end
            header = obj.Cache.Header;
        end
        
        function set.Header(obj, header)
            %set.Header Set the value for property Header
            validateattributes(header, {obj.StdMsgsHeaderClass}, {'nonempty', 'scalar'}, 'GpsCustomCartesian', 'Header');
            
            obj.JavaMessage.setHeader(header.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Header)
                obj.Cache.Header.setJavaObject(header.getJavaObject);
            end
        end
        
        function position = get.Position(obj)
            %get.Position Get the value for property Position
            if isempty(obj.Cache.Position)
                obj.Cache.Position = feval(obj.GeometryMsgsPointClass, obj.JavaMessage.getPosition);
            end
            position = obj.Cache.Position;
        end
        
        function set.Position(obj, position)
            %set.Position Set the value for property Position
            validateattributes(position, {obj.GeometryMsgsPointClass}, {'nonempty', 'scalar'}, 'GpsCustomCartesian', 'Position');
            
            obj.JavaMessage.setPosition(position.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Position)
                obj.Cache.Position.setJavaObject(position.getJavaObject);
            end
        end
        
        function velocityx = get.VelocityX(obj)
            %get.VelocityX Get the value for property VelocityX
            velocityx = double(obj.JavaMessage.getVelocityX);
        end
        
        function set.VelocityX(obj, velocityx)
            %set.VelocityX Set the value for property VelocityX
            validateattributes(velocityx, {'numeric'}, {'nonempty', 'scalar'}, 'GpsCustomCartesian', 'VelocityX');
            
            obj.JavaMessage.setVelocityX(velocityx);
        end
        
        function velocityy = get.VelocityY(obj)
            %get.VelocityY Get the value for property VelocityY
            velocityy = double(obj.JavaMessage.getVelocityY);
        end
        
        function set.VelocityY(obj, velocityy)
            %set.VelocityY Set the value for property VelocityY
            validateattributes(velocityy, {'numeric'}, {'nonempty', 'scalar'}, 'GpsCustomCartesian', 'VelocityY');
            
            obj.JavaMessage.setVelocityY(velocityy);
        end
        
        function positioncovariance = get.PositionCovariance(obj)
            %get.PositionCovariance Get the value for property PositionCovariance
            javaArray = obj.JavaMessage.getPositionCovariance;
            array = obj.readJavaArray(javaArray, 'double');
            positioncovariance = double(array);
        end
        
        function set.PositionCovariance(obj, positioncovariance)
            %set.PositionCovariance Set the value for property PositionCovariance
            validateattributes(positioncovariance, {'numeric'}, {'vector', 'numel', 9}, 'GpsCustomCartesian', 'PositionCovariance');
            
            javaArray = obj.JavaMessage.getPositionCovariance;
            array = obj.writeJavaArray(positioncovariance, javaArray, 'double');
            obj.JavaMessage.setPositionCovariance(array);
        end
        
        function velocitycovariance = get.VelocityCovariance(obj)
            %get.VelocityCovariance Get the value for property VelocityCovariance
            javaArray = obj.JavaMessage.getVelocityCovariance;
            array = obj.readJavaArray(javaArray, 'double');
            velocitycovariance = double(array);
        end
        
        function set.VelocityCovariance(obj, velocitycovariance)
            %set.VelocityCovariance Set the value for property VelocityCovariance
            validateattributes(velocitycovariance, {'numeric'}, {'vector', 'numel', 4}, 'GpsCustomCartesian', 'VelocityCovariance');
            
            javaArray = obj.JavaMessage.getVelocityCovariance;
            array = obj.writeJavaArray(velocitycovariance, javaArray, 'double');
            obj.JavaMessage.setVelocityCovariance(array);
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Header = [];
            obj.Cache.Position = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.VelocityX = obj.VelocityX;
            cpObj.VelocityY = obj.VelocityY;
            cpObj.PositionCovariance = obj.PositionCovariance;
            cpObj.VelocityCovariance = obj.VelocityCovariance;
            
            % Recursively copy compound properties
            cpObj.Header = copy(obj.Header);
            cpObj.Position = copy(obj.Position);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.VelocityX = strObj.VelocityX;
            obj.VelocityY = strObj.VelocityY;
            obj.PositionCovariance = strObj.PositionCovariance;
            obj.VelocityCovariance = strObj.VelocityCovariance;
            obj.Header = feval([obj.StdMsgsHeaderClass '.loadobj'], strObj.Header);
            obj.Position = feval([obj.GeometryMsgsPointClass '.loadobj'], strObj.Position);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.VelocityX = obj.VelocityX;
            strObj.VelocityY = obj.VelocityY;
            strObj.PositionCovariance = obj.PositionCovariance;
            strObj.VelocityCovariance = obj.VelocityCovariance;
            strObj.Header = saveobj(obj.Header);
            strObj.Position = saveobj(obj.Position);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.asctec_hl_comm.GpsCustomCartesian.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.asctec_hl_comm.GpsCustomCartesian;
            obj.reload(strObj);
        end
    end
end
