classdef WaypointResult < robotics.ros.Message
    %WaypointResult MATLAB implementation of asctec_hl_comm/WaypointResult
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'asctec_hl_comm/WaypointResult' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '3f4c97ad97360a3554493ebd7d1ee895' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        GeometryMsgsPoint32Class = robotics.ros.msg.internal.MessageFactory.getClassForType('geometry_msgs/Point32') % Dispatch to MATLAB class for message type geometry_msgs/Point32
        StdMsgsHeaderClass = robotics.ros.msg.internal.MessageFactory.getClassForType('std_msgs/Header') % Dispatch to MATLAB class for message type std_msgs/Header
    end
    
    properties (Dependent)
        Header
        ResultPos
        ResultYaw
        Status
    end
    
    properties (Access = protected)
        Cache = struct('Header', [], 'ResultPos', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Header', 'ResultPos', 'ResultYaw', 'Status'} % List of non-constant message properties
        ROSPropertyList = {'header', 'result_pos', 'result_yaw', 'status'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = WaypointResult(msg)
            %WaypointResult Construct the message object WaypointResult
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function header = get.Header(obj)
            %get.Header Get the value for property Header
            if isempty(obj.Cache.Header)
                obj.Cache.Header = feval(obj.StdMsgsHeaderClass, obj.JavaMessage.getHeader);
            end
            header = obj.Cache.Header;
        end
        
        function set.Header(obj, header)
            %set.Header Set the value for property Header
            validateattributes(header, {obj.StdMsgsHeaderClass}, {'nonempty', 'scalar'}, 'WaypointResult', 'Header');
            
            obj.JavaMessage.setHeader(header.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Header)
                obj.Cache.Header.setJavaObject(header.getJavaObject);
            end
        end
        
        function resultpos = get.ResultPos(obj)
            %get.ResultPos Get the value for property ResultPos
            if isempty(obj.Cache.ResultPos)
                obj.Cache.ResultPos = feval(obj.GeometryMsgsPoint32Class, obj.JavaMessage.getResultPos);
            end
            resultpos = obj.Cache.ResultPos;
        end
        
        function set.ResultPos(obj, resultpos)
            %set.ResultPos Set the value for property ResultPos
            validateattributes(resultpos, {obj.GeometryMsgsPoint32Class}, {'nonempty', 'scalar'}, 'WaypointResult', 'ResultPos');
            
            obj.JavaMessage.setResultPos(resultpos.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.ResultPos)
                obj.Cache.ResultPos.setJavaObject(resultpos.getJavaObject);
            end
        end
        
        function resultyaw = get.ResultYaw(obj)
            %get.ResultYaw Get the value for property ResultYaw
            resultyaw = single(obj.JavaMessage.getResultYaw);
        end
        
        function set.ResultYaw(obj, resultyaw)
            %set.ResultYaw Set the value for property ResultYaw
            validateattributes(resultyaw, {'numeric'}, {'nonempty', 'scalar'}, 'WaypointResult', 'ResultYaw');
            
            obj.JavaMessage.setResultYaw(resultyaw);
        end
        
        function status = get.Status(obj)
            %get.Status Get the value for property Status
            status = char(obj.JavaMessage.getStatus);
        end
        
        function set.Status(obj, status)
            %set.Status Set the value for property Status
            validateattributes(status, {'char'}, {}, 'WaypointResult', 'Status');
            
            obj.JavaMessage.setStatus(status);
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Header = [];
            obj.Cache.ResultPos = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.ResultYaw = obj.ResultYaw;
            cpObj.Status = obj.Status;
            
            % Recursively copy compound properties
            cpObj.Header = copy(obj.Header);
            cpObj.ResultPos = copy(obj.ResultPos);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.ResultYaw = strObj.ResultYaw;
            obj.Status = strObj.Status;
            obj.Header = feval([obj.StdMsgsHeaderClass '.loadobj'], strObj.Header);
            obj.ResultPos = feval([obj.GeometryMsgsPoint32Class '.loadobj'], strObj.ResultPos);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.ResultYaw = obj.ResultYaw;
            strObj.Status = obj.Status;
            strObj.Header = saveobj(obj.Header);
            strObj.ResultPos = saveobj(obj.ResultPos);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.asctec_hl_comm.WaypointResult.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.asctec_hl_comm.WaypointResult;
            obj.reload(strObj);
        end
    end
end
