classdef viconGrabPoseRequest < robotics.ros.Message
    %viconGrabPoseRequest MATLAB implementation of vicon_bridge/viconGrabPoseRequest
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2016 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'vicon_bridge/viconGrabPoseRequest' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '4045133337c2e7a711effc5b44dfbbb6' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        SubjectName
        SegmentName
        NMeasurements
    end
    
    properties (Constant, Hidden)
        PropertyList = {'NMeasurements', 'SegmentName', 'SubjectName'} % List of non-constant message properties
        ROSPropertyList = {'n_measurements', 'segment_name', 'subject_name'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = viconGrabPoseRequest(msg)
            %viconGrabPoseRequest Construct the message object viconGrabPoseRequest
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function subjectname = get.SubjectName(obj)
            %get.SubjectName Get the value for property SubjectName
            subjectname = char(obj.JavaMessage.getSubjectName);
        end
        
        function set.SubjectName(obj, subjectname)
            %set.SubjectName Set the value for property SubjectName
            validateattributes(subjectname, {'char'}, {}, 'viconGrabPoseRequest', 'SubjectName');
            
            obj.JavaMessage.setSubjectName(subjectname);
        end
        
        function segmentname = get.SegmentName(obj)
            %get.SegmentName Get the value for property SegmentName
            segmentname = char(obj.JavaMessage.getSegmentName);
        end
        
        function set.SegmentName(obj, segmentname)
            %set.SegmentName Set the value for property SegmentName
            validateattributes(segmentname, {'char'}, {}, 'viconGrabPoseRequest', 'SegmentName');
            
            obj.JavaMessage.setSegmentName(segmentname);
        end
        
        function nmeasurements = get.NMeasurements(obj)
            %get.NMeasurements Get the value for property NMeasurements
            nmeasurements = int32(obj.JavaMessage.getNMeasurements);
        end
        
        function set.NMeasurements(obj, nmeasurements)
            %set.NMeasurements Set the value for property NMeasurements
            validateattributes(nmeasurements, {'numeric'}, {'nonempty', 'scalar'}, 'viconGrabPoseRequest', 'NMeasurements');
            
            obj.JavaMessage.setNMeasurements(nmeasurements);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.SubjectName = obj.SubjectName;
            cpObj.SegmentName = obj.SegmentName;
            cpObj.NMeasurements = obj.NMeasurements;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.SubjectName = strObj.SubjectName;
            obj.SegmentName = strObj.SegmentName;
            obj.NMeasurements = strObj.NMeasurements;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.SubjectName = obj.SubjectName;
            strObj.SegmentName = obj.SegmentName;
            strObj.NMeasurements = obj.NMeasurements;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.vicon_bridge.viconGrabPoseRequest.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.vicon_bridge.viconGrabPoseRequest;
            obj.reload(strObj);
        end
    end
end
